sudo: required
language: node_js
node_js: "9"

branches:
  only:
    - master

notifications:
  email: false

git:
  depth: 3
  submodules: false

env:
  global:
    - LOGS_DIR=/tmp/logs

stages:
  - name: precache
  - name: lint
  - name: test
  - name: deploy  

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - rm -rf node_modules/ngx-select-ex

install:
  - npm install > /dev/null
  - npm run build > /dev/null

jobs:
  fast_finish: true
  include:
# precache npm and apt dependencies
    - stage: precache
      install: npm install > /dev/null
      script: true
      addons:
        chrome: stable
        apt:
          sources:
          - ubuntu-toolchain-r-test
          # required by node-gyp to build some packages
          packages:
          - g++-4.8
#   lint code
    - stage: lint
      install: true
      script: npm run lint
#   test
    - stage: test
      script: npm run test-coverage
      after_success:
        - ./node_modules/.bin/codecov
#   deploy
    - stage: deploy
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          branch: master
          tags: true

# cache
cache:
  apt: true
  npm: true
  directories:
    - node_modules


